# Site settings
title: Benton County Career Convention
description: The Benton County High School Career Convention is a partnership between the Corvallis School District 509J, Oregon State University's College of Business (COB), Austin Entrepreneurship Program (AEP), Enactus, Benton County High Schools, Corvallis Public Schools Foundation, and Corvallis Chamber of Commerce.
baseurl: "/benton-county-career-convention"
url: "http://peter.coffee/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown


# Special Stuff for the Career Convention
cc-year: 2018
cc-month: "Feburary"
cc-date: "20"
cc-day: "Tuesday"
cc-start-time: "9:30 AM"
cc-end-time: "2:15 PM"
cc-location: "Oregon State University CH2M Hill Alumni Center and LaSells Stewart Center"

cc-student-registration-open: false
cc-student-registration-date: 2017-12-01 09:00:00

cc-contact-name: "Donna Keim"
cc-contact-role: "Chair"
cc-contact-phone: "541-740-1309"
cc-contact-email: "Donna.Keim@corvallis.k12.or.us"

cc-resources-base-url: "downloads/"
cc-resources:
  # - name: "Volunteer Event Information"
  #   file-name: ""
  #   type: "volunteer"
  # - name: "Student Event Information"
  #   file-name: ""
  #   type: "student"
  # - name: "Flyer"
  #   file-name: ""
  - name: "Interviewing Tips"
    file-name: "tips-for-students.pdf"
    type: "student"
  - name: "Mock Interview Event Handout"
    file-name: "mock-interview-sheet-2016.doc"
    type: "volunteer"
  # - name: "Convention Room Schedule"
  #   file-name: ""
  - name: "Message from the Superintendent"
    file-name: "superintendent-note.pdf"
    homepage: true
    subtitle: Letter from the Superintendent
  - name: "Skill Based Resume Example"
    file-name: "skill-resume.pdf"
    type: "student"
  - name: "CIS Resume Example"
    file-name: "cis-resume.pdf"
    type: "student"
  - name: "Active Professional's Resume"
    file-name: "peter-ramsing-resume.pdf"
    type: "student"
  # - name: "Directions"
  #   file-name: ""
  #   homepage: true
  #   subtitle: Directions and Interactive Map
  # - name: "Conference Center Map"
  #   file-name: ""
  #   homepage: true
  #   subtitle: Map of CH2M Hill and Alumni Center
  # - name: "Career Speaker Evaluation"
  #   file-name: ""
  #   type: "student"
  - name: "Career Speaker Reflection"
    file-name: "career-speaker-reflections.pdf"
    type: "student"
  # - name: "Event Information"
  #   file-type: ""
  #   type: "sponsor"

cc-registration-links:
  - name: "Student Registration"
    subtitle: "Register for the Career Convention"
    type: "student"
    url: "https://docs.google.com/forms/d/e/1FAIpQLSeiWYPtM_XZaAx_nAksIDwnLuQoH6kJgGyZ2rtk5ICWWReLhw/viewform"
  - name: "Sponsor/Booth Registration"
    subtitle: "Register to sponsor a booth and engage with students"
    type: "sponsor"
    url: "https://docs.google.com/forms/d/e/1FAIpQLSfoq8G6af4UqgIJcJiS0DNnaSm1jkeus0kh7Bbt5_thF7fAAg/viewform"
  - name: "Career Speaker Registration"
    subtitle: "Register to be a career speaker"
    type: "volunteer"
    url: "https://docs.google.com/forms/d/e/1FAIpQLScpDjjNOw3P6uU_MJPGglkbpzPcAR9joUK5w1BCnYg9AC1E5A/viewform"
  - name: "Mock Interview Registration"
    subtitle: "Register to be a Mock Interviewer"
    type: "volunteer"
    url: "https://docs.google.com/forms/d/e/1FAIpQLSdW4I2Wtx8bZ1MQ71JrbzTSmIc_ZzVK9ujLmDuvcLAePkdawQ/viewform"
  - name: "Event Volunteer Registration"
    subtitle: "Registration for General Assistance"
    type: "volunteer"
    url: "https://docs.google.com/forms/d/e/1FAIpQLSfe9GcGeH3AffGqW_aqE7x5TAx2IHxL52KuFZYnTJiRjSkS9g/viewform"

cc-sponsors-levels:
  - name: "Business Booth"
    type: "booth"
    available: true
    cost: "Free this year!"
    note: "Business Booth Representatives: Please check-in at the registration table in the LaSells Stewart Center and have your booths set-up no later than 9:30 a.m. Volunteers will be on hand to help booth representatives unload vehicles and set-up booths. Business booths will be located in the LaSells Stewart Center, as well as the CH2M Hill Alumni Center. If needed, power cords will be available."
    perks:
      - "Interaction with hundreds of students"
      - "1 Booth"
  - name: "Honor"
    type: "honor"
    available: false
    cost: "$250"
    helps: 25
    perks:
      - "Name on Website"
      - "Interaction with hundreds of students"
      - "1 Booth"
      - "Logo displayed during convention"
      - "Tax Deduction"
  - name: "Grand"
    type: "grand"
    available: false
    cost: "$500"
    helps: 50
    perks:
      - "Name on Website"
      - "Interaction with hundreds of students"
      - "2 Booths: one per venue or one double booth"
      - "Logo displayed during convention"
      - "Bag Inserts Option"
      - "Tax Deduction"
  - name: "Premier"
    type: "premier"
    cost: "$1,500"
    helps: 150
    perks:
      - "Name on Website"
      - "Interaction with hundreds of students"
      - "3 Booths: one single and one double at both venues or one triple"
      - "Logo displayed during convention"
      - "Bag Inserts Option"
      - "Corvallis Flyer Ad"
      - "Tax Deduction"

cc-sponsors:
  - name: "Corvallis Public School District 509J"
    logo: "FIXME"
    type: "premeir"
  - name: "Corvallis Rotary"
    logo: "/img/sponsors/corvallis-rotary-club.png"
    type: "grand"
  - name: "NuScale Power"
    logo: "FIXME"
    type: "grand"
  - name: "HP Inc."
    logo: "FIXME"
    type: "grand"
  - name: "Pipeline Program"
    logo: "/img/sponsors/pipeline-program.png"
    type: "honor"
  - name: "IHA"
    logo: "FIXME"
    type: "honor"
  - name: "LB iLearn Online"
    logo: "FIXME"
    type: "honor"
  - name: "OSU College of Earth, Ocean, and Atmospheric Science" #FIXME: Spelling
    logo: "FIXME"
    type: "honor"

cc-web-creator-name: "Peter Ramsing"
cc-web-creator-url: http://peter.coffee
