# Site settings
title: Benton County Career Convention
description: The Benton County High School Career Convention is a partnership between the Corvallis School District 509J, Oregon State University's College of Business (COB), Austin Entrepreneurship Program (AEP), Enactus, Benton County High Schools, Corvallis Public Schools Foundation, and Corvallis Chamber of Commerce.
baseurl: "" # the subpath of your site, e.g. /blog
url: "REPLACE_ME" # the base hostname & protocol for your site

# Build settings
markdown: kramdown


# Special Stuff for the Career Convention
cc-year: 2017
cc-month: "Feburary"
cc-date: "23"
cc-day: "Tuesday"
cc-start-time: "9:30 AM"
cc-end-time: "2:15 PM"
cc-location: "Oregon State University CH2M Hill Alumni Center and LaSells Stewart Center"

cc-sponsors-premier:
  -

cc-sponsors-grand:
  -

cc-sponsors-honor:
  -

cc-student-registration-date: 2016-12-01 09:00:00

cc-contact-name: "Donna Keim"
cc-contact-role: "Chair"
cc-contact-phone: "541-740-1309"
cc-contact-email: "Donna.Keim@corvallis.k12.or.us"

cc-resources-base-url: "downloads/"
cc-resources:
  - name: "Volunteer Event Information"
    file-name: ""
    type: "volunteer"
  - name: "Student Event Information"
    file-name: ""
    type: "student"
  - name: "Flyer"
    file-name: ""
  - name: "Interviewing Tips"
    file-name: ""
    type: "student"
  - name: "Mock Interview Event Handout"
    file-name: ""
  - name: "Convention Room Schedule"
    file-name: ""
  - name: "Message from the Superintendent"
    file-name: ""
    homepage: true
    subtitle: Letter from the Superintendent
  - name: "Skill Based Resume Example"
    file-name: ""
    type: "student"
  - name: "Chronological Resume Example"
    file-name: ""
    type: "student"
  - name: "CIS Resume Example"
    file-name: ""
    type: "student"
  - name: "Directions"
    file-name: ""
    homepage: true
    subtitle: Directions and Interactive Map
  - name: "Conference Center Map"
    file-name: ""
    homepage: true
    subtitle: Map of CH2M Hill and Alumni Center
  - name: "Career Speaker Evaluation"
    file-name: ""
    type: "student"

cc-registration-links:
  - name: "Student Registration"
    subtitle: "Register for the Career Convetion"
    type: "student"
    ur: ""
  - name: "Sponsor Registration"
    subtitle: "Register to sponsor the Career Convetion"
    type: "sponsor"
    ur: ""
  - name: "Career Speaker Registration"
    subtitle: "Register to be a career speaker"
    type: "career"
    ur: ""
  - name: "Mock Intervier Registration"
    subtitle: "Register to be a Mock Interviewer"
    type: "mock"
    ur: ""
  - name: "Event Volunteer Registration"
    subtitle: "Registration for General Assistance"
    type: "volunteer"
    ur: ""



cc-web-creator-name: "Peter Ramsing"
cc-web-creator-url: http://peter.coffee
